meme_files = [
	"Adam.jpg",
	"arguing.jpg",
	"charity.jpg",
	"decision.jpg",
	"Jesse.jpg",
	"Lions.jpg",
	"Mielke.jpg",
	"my team.jpg",
	"No idea.jpg",
	"Owen.jpg",
	"Scott.jpg",
	"Spaeth.jpg",
	"Steve C.jpg",
	"Steve S.jpg",
	"stfu.jpg",
	"Trevor.jpg",
	"yoda.jpg",
	"you suck.jpg",
	"cowboys.jpg",
	"Jimmy.jpg",
	"dumbass.jpg"
]