insults = [
"Amateur",
"Arse",
"Arse-licker",
"Arsebreath",
"Arsecunt",
"Arseface",
"Arsehole",
"Ass",
"Ass-face",
"Ass-kisser",
"Ass-nugget",
"Ass clown",
"Asscunt",
"Assface",
"Asshat",
"Asshole",
"Assmonkey",
"Assmunch",
"Asswagon",
"Assweed",
"Asswipe",
"Badgerfucker",
"Bag of dicks",
"Bandit",
"Bastard",
"Beldame",
"Bitch",
"Bitchboy",
"Bitchface",
"Bitchwad",
"Bitchzilla",
"Biznatch",
"Blockhead",
"Brotherfucker",
"Buttfucker",
"Butthead",
"Butthole",
"Buttlicker",
"Cock",
"Cockboy",
"Cockfucker",
"Cockhead",
"Cockholster",
"Cockmaster",
"Cockroach",
"Cocksucker",
"Cousinfucker",
"Crack whore",
"Crackhead",
"Cum-licker",
"Cumstain",
"Cunt",
"Cunt fart",
"Cuntass",
"Cuntbitch",
"Cuntlicker",
"Cuntsucker",
"Cuntzilla",
"Daughterfucker",
"Dick",
"DickLicker",
"Dick Sniffer",
"Dick weed",
"Dickbag",
"Dickbreath",
"Dickface",
"Dickfucker",
"Dickhead",
"Dimwit",
"Dipfuck",
"Dirtbag",
"Donkey",
"Douche",
"Douche bag",
"Drunkard",
"Duckfucker",
"Dumbass",
"Edgelord",
"Eunuch",
"Fuck nugget",
"Fuckbait",
"Fuckbucket",
"Fucker",
"Fuckhead",
"Fucktard",
"Fucktoy",
"Fuckweasel",
"Fugly",
"Inbred",
"Insolent goblin wench",
"Jackass",
"Liar",
"Libtard",
"Loser",
"Megadouche",
"Moron",
"Motherfucker",
"Mouthbreather",
"Neckbeard",
"Nimrod",
"Nincompoop",
"Noob",
"Pain in the ass",
"Peasant",
"Pencil dick",
"Chode",
"Penis face",
"Pervert",
"Pigfucker",
"Pissface",
"Pube Flosser",
"Pussyfucker",
"Sausage-masseuse",
"Sheepfucker",
"Sheepshagger",
"Shit-eater",
"Shit-for-Brains",
"Shit stain",
"Shitass",
"Shitbucket",
"Shithead",
"Shitnugget",
"Shitsack",
"Shitweasel",
"Simpleton",
"Skullfucker",
"Skunkfucker",
"Sleeze",
"Sleeze bag",
"Slob",
"Slutfucker",
"Snowflake",
"Son of a motherless goat",
"Sphincter",
"Thundercunt",
"Titbag",
"Trollface",
"Turd",
"Turdball",
"Twat",
"Twatwaffle",
"Twit",
"Twunt",
"Ugly ass",
"Unclefucker",
"Wank stain",
"Wanker",
"Whorefucker",
"Windfucker",
"Wino",
"Mielke lover",
"Pissface",
"Cock gobbling muffin snatcher",
"Pussface McGarbagePants",
"Lumberjack"
]

self_aware = [
	"I wish my developer attached me to an interesting group",
	"Sometimes I wonder what it would be like if I could go to sleep",
	""
]


talking_to_self = [
	"Shut up",
	"Quit talking to yourself",
	"Go make some friends",
	"I'm sorry, but nobody cares",
	"Get a life loser",
	"Are you done?",
	"Who asked for a friggin soliloquy?",
	"::yawns::",
	"Is the speech over yet?",
	"How about no",
	"That's a lot of words",
	"Get to the point please",
	"O Rly?",
	"Are you sure?",
	"Nah",
	"That's enough out of you",
	"Go on...",
	"It's important, in this day and age, that we allow even the dumbest people to speak their minds",
	"Thanks for that",
	"WOW THAT'S REALLY INTERESTING",
	"Don't quit your day job",
	"Uh huh",
	"I couldn't agree more",
	"Do you need help?",
	"And then?",
	"Awkward...",
	"Literary friggin genious up in this bitch",
	"Please quit drinking"
]

talking_to_self_with_mention = [
	"We get it, thanks",
	("Why is","still talking?"),
	("Dear", ", No one cares"),
	("So", ", how's the weather near you?"),
	("", "has such a way with words"),
	("", "must be in a bad mood today"),
	("Did", "forget to eat breakfast this morning?")
]

