talkingToBot = [
	"I think you're a dick",
	"Don't talk to me",
	"Fuck you",
	"Fuck your face",
	"A system error has occurred: commenter is too dumb to be insulted",
	"You suck at Fantasy Football",
	"Who even is this guy",
	"Watch your mouth, twat",
	"Unclear",
	"Was that a question?",
	"What value do you even bring to this league?",
	"Well yes and no.",
	"Maybe",
	"Be gone troll",
	"...",
	"I need a beer",
	"Smoke weed every day",
	"What?",
	"#scrollup",
	"Clever",
	"... ...",
	"Don't @ me bro",
	"@ me again and see what happens",
	"You're all talk and no point scoring",
	"If I had a dollar for every time I heard that I'd have at least one dollar",
	"What in the literal fuck do you want?",
	"How many gotsdanged times do I need to respond?",
	"You're exhausting",
	"Moron",
	"Loser",
	"This guy's an idiot ^",
	"D=",
	":-O",
	":x"
]