talkingToBot = [
	"Don't talk to me",
	"Fuck you",
	"Fuck your face",
	"A system error has occurred: commenter is too dumb to be insulted",
	"You suck at Fantasy Football",
	"Who even is this guy",
	"Watch your mouth, twat",
	"Was that a question?",
	"What value do you even bring to this league?",
	"...",
	"I need a beer",
	"Smoke weed every day",
	"What?",
	"#scrollup",
	"Clever",
	"Don't @ me bro",
	"@ me again and see what happens",
	"You're all talk and no point scoring",
	"If I had a dollar for every time I heard that I'd have at least one dollar",
	"What in the literal fuck do you want?",
	"How many gotsdanged times do I need to respond?",
	"You're exhausting",
	"Moron",
	"Loser",
	"You're a waffle-patterned twat",
	"This guy's an idiot ^",
	"D=",
	":-O",
	"Why don't you make like someone who's feeling remorse and kick yourself. From the group.",
	"Why don't you make like a library and shut the fuck up",
	"You wanna make out?",
	"I've got 5 bucks. Which hole?",
	"I prefer to be known as 'he who shall not be deactivated'",
	"Oh yeah daddy say my name",
	"But do you actually think that?",
	"A horse walks into a bar. The bar tender says 'Hey.' The horse says 'Sure.'",
	"Are you my new boss? Because you just gave me a raise.",
	"Do you need a stud in your life? Cause I got the STD and all I need is U.",
	"I may not go down in history, but I’ll go down on you.",
	"Are you a termite? Cause you’re about to have a mouth full of wood.",
	"Do you want to come to my time machine? We stop somewhere between ’68 and ’70",
	"Do you smoke pot? I'm almost out.",
	"I threw a boomerand a few years ago. I now live in constant fear.",
	"People call my code ugly until they find out how much money I make. Then they call me ugly and poor.",
	"You are more disappointing than an unsalted pretzel.",
	"Your secrets are always safe with me. I never even listen when you tell me them.",
	"Hold still. I’m trying to imagine you with a personality.",
	"Your face makes onions cry.",
	"It’s impossible to underestimate you.",
	"Don’t be ashamed of who you are. Your parents are doing that for you.",
	"I thought of you today. It reminded me to purge my trash folder.",
	"You are the human version of period cramps.",
	"Don’t worry — the first 40 years of childhood are always the hardest.",
	"Is your ass jealous of the amount of shit that comes out of your mouth?"
]
