responses = [
    ["What do you call a Jets fan with half a brain?", "Gifted!"],
    ["What do you get when you put a dozen Crimson Tide fans in one room?", "A full set of teeth"],
    #["You're trapped in a room with an angry grizzly bear, a hungry lion, and a fan of the Dallas Cowboys. You have a gun with two bullets. What should you do?","Shoot the Cowboys fan twice."],
    #["How do you keep the Detroit Lions out of your front yard?", "Put up goal posts"],
    ["What kind of tea does Ndamukong Suh drink?", "Penaltea!"],
    #["Why is your team like a diaper?","It's usually full of shit, but thankfully disposable."],
    ["What was worse through the first three weeks: Mark's Fantasy Football management or his football team?", "Trick question! They're both the worst."],
    ["What goes in hard and dry then comes out wet and soft?", "A penis!"],
    #["What do you do with a year’s worth of used condoms?", "Idk use them or something"],
    ["What does the receptionist at a sperm bank say as clients leave?", "Thank you for coming!"],
    ["Which sexual position produces the ugliest kids?", "Ask your mom"],
    #["How is pubic hair like parsley?", "You push it to the side before you start eating."],
    #["What’s red and bad for your teeth?", "A brick"],
    #["How many Germans does it take to screw in a lightbulb?", "One"]
    ["What percent of the world's fresh water is frozen in glaciers?", "69%. Nice."],
    ["What was the fastest gust of wind ever recorded?", "253 MPH. Measured from Steve C's complaining."],
    ["What is Mark's favorite weekend activity?", "Losing"],
    ["What is the most popular travel destination (country) in the world?", "France"],
    ["What are the Canary islands named after?", "Canariae Insulae means 'island of dogs.'"],
    ["Did you know 4 babies are born every second?", "Steve C's whining makes up 20% of them"],
    ["The coldest temperature recorded on eart is -144*", "It was measured from Owen's heart"],
    ["The Earth's ozone layer will make a full recovery in 50 years","Maulik's team will not"],
    ["What is the mortality rate among the current population on Earth?", "0%"],
    ["Muhammed is thought to be the most popular name in the world", "Jesse is considered the least popular human being in the world"],
    ["When does Spaeth eat a fancy dinner?", "After posting it to Instagram"],
]