"""empty message

Revision ID: 1845abef3b1d
Revises: 
Create Date: 2021-06-13 11:16:33.958880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1845abef3b1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupId', sa.String(), nullable=True),
    sa.Column('botIds', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('counter_lowerBound', sa.Integer(), nullable=True),
    sa.Column('counter_upperBound', sa.Integer(), nullable=True),
    sa.Column('counter_currentThreshold', sa.Integer(), nullable=True),
    sa.Column('counter_current', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    # ### end Alembic commands ###
