"""empty message

Revision ID: 184840bba4de
Revises: 
Create Date: 2021-08-22 21:11:05.718723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184840bba4de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inboundMessages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messageText', sa.String(), nullable=True),
    sa.Column('createdDateTime', sa.DateTime(), nullable=True),
    sa.Column('groupId', sa.String(), nullable=True),
    sa.Column('sendingUser', sa.String(), nullable=True),
    sa.Column('sendingUserType', sa.String(), nullable=True),
    sa.Column('outboundMessageId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groupId'], ['groups.groupId'], ),
    sa.ForeignKeyConstraint(['outboundMessageId'], ['outboundMessages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_table('inboundMessages')
    # ### end Alembic commands ###
