"""empty message

Revision ID: 41caffd1dbf1
Revises: 58ebffe1f22a
Create Date: 2021-06-19 10:56:34.359987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41caffd1dbf1'
down_revision = '58ebffe1f22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('messageTypes', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('groups', 'message_types')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('message_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('groups', 'messageTypes')
    # ### end Alembic commands ###
