"""empty message

Revision ID: 58ebffe1f22a
Revises: bda203b177d2
Create Date: 2021-06-19 09:47:18.853870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58ebffe1f22a'
down_revision = 'bda203b177d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupId', sa.String(), nullable=True),
    sa.Column('groupName', sa.String(), nullable=True),
    sa.Column('botIds', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('counter_lowerBound', sa.Integer(), nullable=True),
    sa.Column('counter_upperBound', sa.Integer(), nullable=True),
    sa.Column('counter_currentThreshold', sa.Integer(), nullable=True),
    sa.Column('counter_current', sa.Integer(), nullable=True),
    sa.Column('message_types', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('messagingServiceStatus', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    # ### end Alembic commands ###
