"""empty message

Revision ID: 5f4d535ffc04
Revises: 1845abef3b1d
Create Date: 2021-06-13 11:56:36.713818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4d535ffc04'
down_revision = '1845abef3b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('groupName', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'groupName')
    # ### end Alembic commands ###
