"""empty message

Revision ID: 8072e625be8d
Revises: 
Create Date: 2021-06-20 07:07:13.174412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8072e625be8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bot_name', sa.String(), nullable=True),
    sa.Column('callbackUrl', sa.String(), nullable=True),
    sa.Column('avatarUrl', sa.String(), nullable=True),
    sa.Column('createdDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupId', sa.String(), nullable=True),
    sa.Column('groupName', sa.String(), nullable=True),
    sa.Column('botId', sa.String(), nullable=True),
    sa.Column('counter_lowerBound', sa.Integer(), nullable=True),
    sa.Column('counter_upperBound', sa.Integer(), nullable=True),
    sa.Column('counter_currentThreshold', sa.Integer(), nullable=True),
    sa.Column('counter_current', sa.Integer(), nullable=True),
    sa.Column('messageTypes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('messagingServiceStatus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['botId'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    op.drop_table('bots')
    # ### end Alembic commands ###
