"""empty message

Revision ID: 880d45c9a188
Revises: 11492e245ef2
Create Date: 2021-07-02 13:06:07.916647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880d45c9a188'
down_revision = '11492e245ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'creatingUser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('creatingUser', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
