"""empty message

Revision ID: bda203b177d2
Revises: 5f4d535ffc04
Create Date: 2021-06-19 09:43:12.495330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bda203b177d2'
down_revision = '5f4d535ffc04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('groupId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('botIds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('counter_lowerBound', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('counter_upperBound', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('counter_currentThreshold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('counter_current', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('groupName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='groups_pkey')
    )
    # ### end Alembic commands ###
