"""empty message

Revision ID: e06cec55a4eb
Revises: 
Create Date: 2021-07-02 13:15:56.693165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e06cec55a4eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('botName', sa.String(), nullable=True),
    sa.Column('callbackUrl', sa.String(), nullable=True),
    sa.Column('avatarUrl', sa.String(), nullable=True),
    sa.Column('createdDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupId', sa.String(), nullable=True),
    sa.Column('groupName', sa.String(), nullable=True),
    sa.Column('botId', sa.String(), nullable=True),
    sa.Column('counter_lowerBound', sa.Integer(), nullable=True),
    sa.Column('counter_upperBound', sa.Integer(), nullable=True),
    sa.Column('counter_currentThreshold', sa.Integer(), nullable=True),
    sa.Column('counter_current', sa.Integer(), nullable=True),
    sa.Column('messageTypes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('messagingServiceStatus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['botId'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outboundMessages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messageText', sa.String(), nullable=True),
    sa.Column('createdDateTime', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('triggeringUser', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outboundMessages')
    op.drop_table('groups')
    op.drop_table('bots')
    # ### end Alembic commands ###
