"""empty message

Revision ID: e45a788928f0
Revises: 8072e625be8d
Create Date: 2021-06-20 07:30:57.300278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45a788928f0'
down_revision = '8072e625be8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('botName', sa.String(), nullable=True))
    op.drop_column('bots', 'bot_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('bot_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bots', 'botName')
    # ### end Alembic commands ###
